# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import course_pb2 as course__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in course_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CourseServiceStub(object):
    """The Course Management Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCourses = channel.unary_unary(
                '/course.CourseService/ListCourses',
                request_serializer=course__pb2.ListCoursesRequest.SerializeToString,
                response_deserializer=course__pb2.ListCoursesResponse.FromString,
                _registered_method=True)
        self.AddCourse = channel.unary_unary(
                '/course.CourseService/AddCourse',
                request_serializer=course__pb2.AddCourseRequest.SerializeToString,
                response_deserializer=course__pb2.AddCourseResponse.FromString,
                _registered_method=True)
        self.CloseCourse = channel.unary_unary(
                '/course.CourseService/CloseCourse',
                request_serializer=course__pb2.CloseCourseRequest.SerializeToString,
                response_deserializer=course__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.UpdateSlots = channel.unary_unary(
                '/course.CourseService/UpdateSlots',
                request_serializer=course__pb2.UpdateSlotsRequest.SerializeToString,
                response_deserializer=course__pb2.OperationResponse.FromString,
                _registered_method=True)


class CourseServiceServicer(object):
    """The Course Management Service definition
    """

    def ListCourses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCourse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseCourse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CourseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCourses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCourses,
                    request_deserializer=course__pb2.ListCoursesRequest.FromString,
                    response_serializer=course__pb2.ListCoursesResponse.SerializeToString,
            ),
            'AddCourse': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCourse,
                    request_deserializer=course__pb2.AddCourseRequest.FromString,
                    response_serializer=course__pb2.AddCourseResponse.SerializeToString,
            ),
            'CloseCourse': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseCourse,
                    request_deserializer=course__pb2.CloseCourseRequest.FromString,
                    response_serializer=course__pb2.OperationResponse.SerializeToString,
            ),
            'UpdateSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSlots,
                    request_deserializer=course__pb2.UpdateSlotsRequest.FromString,
                    response_serializer=course__pb2.OperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'course.CourseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('course.CourseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CourseService(object):
    """The Course Management Service definition
    """

    @staticmethod
    def ListCourses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/course.CourseService/ListCourses',
            course__pb2.ListCoursesRequest.SerializeToString,
            course__pb2.ListCoursesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCourse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/course.CourseService/AddCourse',
            course__pb2.AddCourseRequest.SerializeToString,
            course__pb2.AddCourseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseCourse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/course.CourseService/CloseCourse',
            course__pb2.CloseCourseRequest.SerializeToString,
            course__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/course.CourseService/UpdateSlots',
            course__pb2.UpdateSlotsRequest.SerializeToString,
            course__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
