# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enrollment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'enrollment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65nrollment.proto\x12\nenrollment\"\xaa\x01\n\x0bGradeRecord\x12\x15\n\renrollment_id\x18\x01 \x01(\x05\x12\x11\n\tcourse_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x63ourse_code\x18\x03 \x01(\t\x12\x14\n\x0c\x63ourse_title\x18\x04 \x01(\t\x12\x18\n\x10student_username\x18\x05 \x01(\t\x12\x12\n\x05grade\x18\x06 \x01(\x02H\x00\x88\x01\x01\x12\x0e\n\x06status\x18\x07 \x01(\tB\x08\n\x06_grade\"<\n\rEnrollRequest\x12\x18\n\x10student_username\x18\x01 \x01(\t\x12\x11\n\tcourse_id\x18\x02 \x01(\x05\"I\n\x0e\x45nrollResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\renrollment_id\x18\x03 \x01(\x05\"-\n\x11ViewGradesRequest\x12\x18\n\x10student_username\x18\x01 \x01(\t\">\n\x12ViewGradesResponse\x12(\n\x07records\x18\x01 \x03(\x0b\x32\x17.enrollment.GradeRecord\"T\n\x12UploadGradeRequest\x12\x18\n\x10\x66\x61\x63ulty_username\x18\x01 \x01(\t\x12\x15\n\renrollment_id\x18\x02 \x01(\x05\x12\r\n\x05grade\x18\x03 \x01(\x02\"\x7f\n\x13UploadGradeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rupdated_grade\x18\x03 \x01(\x02\x12/\n\x0eupdated_record\x18\x04 \x01(\x0b\x32\x17.enrollment.GradeRecord2\xf1\x01\n\x11\x45nrollmentService\x12?\n\x06\x45nroll\x12\x19.enrollment.EnrollRequest\x1a\x1a.enrollment.EnrollResponse\x12K\n\nViewGrades\x12\x1d.enrollment.ViewGradesRequest\x1a\x1e.enrollment.ViewGradesResponse\x12N\n\x0bUploadGrade\x12\x1e.enrollment.UploadGradeRequest\x1a\x1f.enrollment.UploadGradeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enrollment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRADERECORD']._serialized_start=33
  _globals['_GRADERECORD']._serialized_end=203
  _globals['_ENROLLREQUEST']._serialized_start=205
  _globals['_ENROLLREQUEST']._serialized_end=265
  _globals['_ENROLLRESPONSE']._serialized_start=267
  _globals['_ENROLLRESPONSE']._serialized_end=340
  _globals['_VIEWGRADESREQUEST']._serialized_start=342
  _globals['_VIEWGRADESREQUEST']._serialized_end=387
  _globals['_VIEWGRADESRESPONSE']._serialized_start=389
  _globals['_VIEWGRADESRESPONSE']._serialized_end=451
  _globals['_UPLOADGRADEREQUEST']._serialized_start=453
  _globals['_UPLOADGRADEREQUEST']._serialized_end=537
  _globals['_UPLOADGRADERESPONSE']._serialized_start=539
  _globals['_UPLOADGRADERESPONSE']._serialized_end=666
  _globals['_ENROLLMENTSERVICE']._serialized_start=669
  _globals['_ENROLLMENTSERVICE']._serialized_end=910
# @@protoc_insertion_point(module_scope)
