# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import enrollment_pb2 as enrollment__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in enrollment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnrollmentServiceStub(object):
    """--- Service Definition ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/enrollment.EnrollmentService/Enroll',
                request_serializer=enrollment__pb2.EnrollRequest.SerializeToString,
                response_deserializer=enrollment__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.ViewGrades = channel.unary_unary(
                '/enrollment.EnrollmentService/ViewGrades',
                request_serializer=enrollment__pb2.ViewGradesRequest.SerializeToString,
                response_deserializer=enrollment__pb2.ViewGradesResponse.FromString,
                _registered_method=True)
        self.UploadGrade = channel.unary_unary(
                '/enrollment.EnrollmentService/UploadGrade',
                request_serializer=enrollment__pb2.UploadGradeRequest.SerializeToString,
                response_deserializer=enrollment__pb2.UploadGradeResponse.FromString,
                _registered_method=True)
        self.Unenroll = channel.unary_unary(
                '/enrollment.EnrollmentService/Unenroll',
                request_serializer=enrollment__pb2.UnenrollRequest.SerializeToString,
                response_deserializer=enrollment__pb2.UnenrollResponse.FromString,
                _registered_method=True)


class EnrollmentServiceServicer(object):
    """--- Service Definition ---
    """

    def Enroll(self, request, context):
        """Students to enroll in an open course
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewGrades(self, request, context):
        """Students to view their previous grades
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadGrade(self, request, context):
        """Faculty to be able to upload grades
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unenroll(self, request, context):
        """Students to unenroll from an existing course
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnrollmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=enrollment__pb2.EnrollRequest.FromString,
                    response_serializer=enrollment__pb2.EnrollResponse.SerializeToString,
            ),
            'ViewGrades': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewGrades,
                    request_deserializer=enrollment__pb2.ViewGradesRequest.FromString,
                    response_serializer=enrollment__pb2.ViewGradesResponse.SerializeToString,
            ),
            'UploadGrade': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadGrade,
                    request_deserializer=enrollment__pb2.UploadGradeRequest.FromString,
                    response_serializer=enrollment__pb2.UploadGradeResponse.SerializeToString,
            ),
            'Unenroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Unenroll,
                    request_deserializer=enrollment__pb2.UnenrollRequest.FromString,
                    response_serializer=enrollment__pb2.UnenrollResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'enrollment.EnrollmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('enrollment.EnrollmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnrollmentService(object):
    """--- Service Definition ---
    """

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrollment.EnrollmentService/Enroll',
            enrollment__pb2.EnrollRequest.SerializeToString,
            enrollment__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewGrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrollment.EnrollmentService/ViewGrades',
            enrollment__pb2.ViewGradesRequest.SerializeToString,
            enrollment__pb2.ViewGradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadGrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrollment.EnrollmentService/UploadGrade',
            enrollment__pb2.UploadGradeRequest.SerializeToString,
            enrollment__pb2.UploadGradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unenroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrollment.EnrollmentService/Unenroll',
            enrollment__pb2.UnenrollRequest.SerializeToString,
            enrollment__pb2.UnenrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
