# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'course.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ourse.proto\x12\x06\x63ourse\"Q\n\x06\x43ourse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\r\n\x05slots\x18\x04 \x01(\x05\x12\x0f\n\x07is_open\x18\x05 \x01(\x08\"\x14\n\x12ListCoursesRequest\"6\n\x13ListCoursesResponse\x12\x1f\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x0e.course.Course\">\n\x10\x41\x64\x64\x43ourseRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05slots\x18\x03 \x01(\x05\"3\n\x11\x41\x64\x64\x43ourseResponse\x12\x1e\n\x06\x63ourse\x18\x01 \x01(\x0b\x32\x0e.course.Course\"\'\n\x12\x43loseCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\":\n\x12UpdateSlotsRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\x05\x12\x11\n\tnew_slots\x18\x02 \x01(\x05\"5\n\x11OperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa5\x02\n\rCourseService\x12\x46\n\x0bListCourses\x12\x1a.course.ListCoursesRequest\x1a\x1b.course.ListCoursesResponse\x12@\n\tAddCourse\x12\x18.course.AddCourseRequest\x1a\x19.course.AddCourseResponse\x12\x44\n\x0b\x43loseCourse\x12\x1a.course.CloseCourseRequest\x1a\x19.course.OperationResponse\x12\x44\n\x0bUpdateSlots\x12\x1a.course.UpdateSlotsRequest\x1a\x19.course.OperationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COURSE']._serialized_start=24
  _globals['_COURSE']._serialized_end=105
  _globals['_LISTCOURSESREQUEST']._serialized_start=107
  _globals['_LISTCOURSESREQUEST']._serialized_end=127
  _globals['_LISTCOURSESRESPONSE']._serialized_start=129
  _globals['_LISTCOURSESRESPONSE']._serialized_end=183
  _globals['_ADDCOURSEREQUEST']._serialized_start=185
  _globals['_ADDCOURSEREQUEST']._serialized_end=247
  _globals['_ADDCOURSERESPONSE']._serialized_start=249
  _globals['_ADDCOURSERESPONSE']._serialized_end=300
  _globals['_CLOSECOURSEREQUEST']._serialized_start=302
  _globals['_CLOSECOURSEREQUEST']._serialized_end=341
  _globals['_UPDATESLOTSREQUEST']._serialized_start=343
  _globals['_UPDATESLOTSREQUEST']._serialized_end=401
  _globals['_OPERATIONRESPONSE']._serialized_start=403
  _globals['_OPERATIONRESPONSE']._serialized_end=456
  _globals['_COURSESERVICE']._serialized_start=459
  _globals['_COURSESERVICE']._serialized_end=752
# @@protoc_insertion_point(module_scope)
